# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_whatsDirect(object):
    def setupUi(self, whatsDirect):
        whatsDirect.setObjectName("whatsDirect")
        whatsDirect.resize(865, 685)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        whatsDirect.setFont(font)
        whatsDirect.setAutoFillBackground(False)
        whatsDirect.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"\n"
"background-color: rgb(186, 189, 182);")
        whatsDirect.setSizeGripEnabled(True)
        self.StartButton = QtWidgets.QPushButton(whatsDirect)
        self.StartButton.setGeometry(QtCore.QRect(500, 570, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.StartButton.setFont(font)
        self.StartButton.setStyleSheet("background-color: rgb(73, 200, 4);\n"
"")
        self.StartButton.setObjectName("StartButton")
        self.CancelButton = QtWidgets.QPushButton(whatsDirect)
        self.CancelButton.setGeometry(QtCore.QRect(200, 570, 211, 51))
        font = QtGui.QFont()
        font.setFamily("12 MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.CancelButton.setFont(font)
        self.CancelButton.setStyleSheet("background-color: rgb(239, 41, 41);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"font: 75 16pt      Bold \"MS Shell Dlg 2\";\n"
"")
        self.CancelButton.setObjectName("CancelButton")
        self.ExcelSheetName = QtWidgets.QLineEdit(whatsDirect)
        self.ExcelSheetName.setGeometry(QtCore.QRect(500, 460, 201, 41))
        self.ExcelSheetName.setText("")
        self.ExcelSheetName.setObjectName("ExcelSheetName")
        self.label = QtWidgets.QLabel(whatsDirect)
        self.label.setGeometry(QtCore.QRect(200, 460, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(whatsDirect)
        self.label_2.setGeometry(QtCore.QRect(200, 520, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.quizzNo = QtWidgets.QLineEdit(whatsDirect)
        self.quizzNo.setGeometry(QtCore.QRect(500, 520, 201, 41))
        self.quizzNo.setText("")
        self.quizzNo.setObjectName("quizzNo")
        self.label_3 = QtWidgets.QLabel(whatsDirect)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 881, 691))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("photo.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.StartButton.raise_()
        self.CancelButton.raise_()
        self.ExcelSheetName.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.quizzNo.raise_()

        self.retranslateUi(whatsDirect)
        QtCore.QMetaObject.connectSlotsByName(whatsDirect)

    def retranslateUi(self, whatsDirect):
        _translate = QtCore.QCoreApplication.translate
        whatsDirect.setWindowTitle(_translate("whatsDirect", "TelegramDirect"))
        self.StartButton.setText(_translate("whatsDirect", "Start"))
        self.CancelButton.setText(_translate("whatsDirect", "Cancel"))
        self.label.setText(_translate("whatsDirect", "Enter Your excel sheet Name"))
        self.label_2.setText(_translate("whatsDirect", "Enter your the last Quizz Number"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    whatsDirect = QtWidgets.QDialog()
    ui = Ui_whatsDirect()
    ui.setupUi(whatsDirect)
    whatsDirect.show()
    sys.exit(app.exec_())
